export const demoJobs = [
  {
    id: 1,
    slug: "multimodal-foundation-expert",
    title: "多模态基模算法专家",
    team: "Foundation Model",
    domain: "大模型与多模态",
    location: "北京 / 深圳 / 杭州",
    employmentType: "全职",
    salaryRange: "面议",
    summary:
      "负责多模态基模的数据、模型与训练体系，推动电商和商业化场景落地。",
    requirements:
      "具备多模态预训练或后训练经验|熟悉数据 Pipeline 与质量评估|有头部基模团队经历优先",
    status: "active",
    createdAt: "2026-07-01T00:00:00.000Z",
    updatedAt: "2026-07-28T00:00:00.000Z",
  },
  {
    id: 2,
    slug: "ai-infra-platform-lead",
    title: "AI Infra 平台负责人",
    team: "AI Systems",
    domain: "AI Infra",
    location: "北京 / 上海",
    employmentType: "全职",
    salaryRange: "面议",
    summary:
      "从 0 到 1 建设大模型训练与推理平台，负责资源效率、稳定性与研发体验。",
    requirements:
      "有千卡级训练平台经验|熟悉调度、容错与可观测性|具备团队管理和跨部门推进能力",
    status: "active",
    createdAt: "2026-07-01T00:00:00.000Z",
    updatedAt: "2026-07-29T00:00:00.000Z",
  },
  {
    id: 3,
    slug: "embodied-learning-scientist",
    title: "具身学习算法科学家",
    team: "Embodied Intelligence",
    domain: "机器人与具身智能",
    location: "北京 / 深圳",
    employmentType: "全职",
    salaryRange: "面议",
    summary:
      "研究并落地机器人强化学习、VLA 与世界模型，打通仿真到真机训练闭环。",
    requirements:
      "具备 RL、模仿学习或 VLA 经验|有真机项目与量产经验优先|硕博背景优先",
    status: "active",
    createdAt: "2026-07-02T00:00:00.000Z",
    updatedAt: "2026-07-29T00:00:00.000Z",
  },
  {
    id: 4,
    slug: "end-to-end-driving-lead",
    title: "端到端自动驾驶算法负责人",
    team: "Autonomous Driving",
    domain: "自动驾驶",
    location: "北京 / 苏州 / 上海",
    employmentType: "全职",
    salaryRange: "面议",
    summary:
      "负责端到端感知与规划算法，推动规模化量产上车和数据闭环建设。",
    requirements:
      "20 人以上团队管理经验优先|有量产上车项目|熟悉世界模型或一段式方案",
    status: "active",
    createdAt: "2026-07-03T00:00:00.000Z",
    updatedAt: "2026-07-29T00:00:00.000Z",
  },
  {
    id: 5,
    slug: "inference-optimization-architect",
    title: "大模型推理优化架构师",
    team: "Inference",
    domain: "AI Infra",
    location: "杭州 / 上海 / 深圳",
    employmentType: "全职",
    salaryRange: "面议",
    summary:
      "面向高并发和长序列场景优化推理系统，覆盖 Prefill/Decode、KV Cache 与异构加速。",
    requirements:
      "熟悉 vLLM 等推理框架|具备 CUDA 或算子优化能力|有实际业务性能指标",
    status: "active",
    createdAt: "2026-07-04T00:00:00.000Z",
    updatedAt: "2026-07-30T00:00:00.000Z",
  },
  {
    id: 6,
    slug: "ai-product-builder",
    title: "AI 产品构建者",
    team: "New Product",
    domain: "AI 产品与设计",
    location: "北京 / 远程",
    employmentType: "全职",
    salaryRange: "面议",
    summary:
      "把用户洞察、模型能力与产品工程连接起来，快速验证 AI 原生产品。",
    requirements:
      "能独立完成产品定义和原型|理解 Agent 与多模态应用|具备数据分析与增长意识",
    status: "active",
    createdAt: "2026-07-05T00:00:00.000Z",
    updatedAt: "2026-07-30T00:00:00.000Z",
  },
] as const;

export const demoTalentProfiles = [
  {
    id: 1,
    name: "陈墨",
    title: "AI Infra · 分布式训练",
    domain: "AI Infra",
    skills: "分布式训练, 推理优化, 调度系统, KV Cache",
    summary: "长期维护训练恢复与推理效率相关开源项目。",
    evidenceCount: 16,
    sourceCount: 9,
    matchScore: 94,
  },
  {
    id: 2,
    name: "林乔",
    title: "具身智能 · 机器人学习",
    domain: "机器人与具身智能",
    skills: "强化学习, VLA, 机器人控制, 仿真",
    summary: "连续三年保持论文、代码与真机验证同步更新。",
    evidenceCount: 14,
    sourceCount: 7,
    matchScore: 91,
  },
  {
    id: 3,
    name: "周也",
    title: "推理架构 · 编译器",
    domain: "AI Infra",
    skills: "编译器, CUDA, 算子优化, 端侧推理",
    summary: "公开演讲、代码贡献与工程项目长期互相印证。",
    evidenceCount: 18,
    sourceCount: 10,
    matchScore: 88,
  },
];
